version: "3.8"

services:

  tweet:
    image: marcellodesales/02022022-time-capsule
    build:
      context: .
      args:
        # The nameo of the main python script 
        # as it will be compiled to binary
        MAIN_FILE_NAME: main

    environment:
      MODE: list

      # Add the test env vars to run the tweet test for the given time
      #MODE: test
      #TWEET_TEST_TIME=204520 

    volumes:
      - /Users/marcellodesales:/root
